package config

// noinspection ALL
const (
	HTTP_PORT       = "HTTP_PORT"
	DATABASE_DRIVER = "DATABASE_DRIVER"
	DATABASE_HOST   = "DATABASE_HOST"
	DATABASE_PORT   = "DATABASE_PORT"
	DATABASE_USER   = "DATABASE_USER"
	DATABASE_PASS   = "DATABASE_PASS"
	DATABASE_NAME   = "DATABASE_NAME"
	DATABASE_SSL    = "DATABASE_SSL"
	TEMP_UPLOAD_DIR = "TEMP_UPLOAD_DIR"
)
